on:
  workflow_dispatch:
  schedule:
    # Run the deploy hourly on the hour.
    - cron: '0 * * * *'
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sign into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: Sign into ACR registry
        run: az acr login --name aiplatcz7m4acr
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Install Promptflow tools
        run: |
          pip install -r ./Consumers/PromptFlow/new-standard-flow-created-at-2024-7-2/requirements.txt
          pip install keyrings.alt

      - name: Build PromptFlow Dockerfile
        run: |
          pf connection create -f ./Consumers/PromptFlow/connections/graeme-apim-backed.yaml --set api_key=${{ secrets.AOAI_KEY }}
          pf flow build --source ./Consumers/PromptFlow/new-standard-flow-created-at-2024-7-2/ --output ./dist --format docker
        
      - name: Build Docker image
        run: |
          docker build -t promptflow-consumer:latest ./dist
        
      - name: Push Docker image
        run: |
          docker build -t aiplatcz7m4acr.azurecr.io/promptflows/consumer-1:latest ./dist

      - name: Push Promptflow Docker image to ACR
        run: docker push aiplatcz7m4acr.azurecr.io/promptflows/consumer-1:latest
